language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: qBOQiCQkuossKo5aYmrd/JBZFAMOdZhd4aseGMzu5xb4K8f2peOlASdvaQSNNkImrYrVTK/jEmitS++dhDeEnPjBxwitOLZ8Y6zRLq6pSRdXnHr+oXB9HO7pE4/lWg7rgLtROsYUjKd/+UgaUJZ6KZX7zVbGzCze1YrdVA7bbkA4HjlylF1EvFebi57fM6jDQ8J+oXp5GsSsoe6R/Gd+tx+G0F8irn489u6XcKgUcX1Asb+lL31uLsNn7n0vlswizJkBD4q4NUlRIss/PpskB6k9et7x0qpLzUOpTEaZDmWZBljNrvYGXHbkbdCrdyo9goRiNA+W76MplYXwVpMn4Mnrydb/Zj2lm+K8XqjPLTiEGS0z7HwbzTeFTenWLLneDaMM01qfhRR0cnzdAajyh3b833dzBL3Qz9+w8Ok3b0wqTwhvcdkm2VgJyThKW5nua8TpbsNZ3Y3QWsWGFF6ex058pJhfXwyoB45MKgWvUvsHM0BmPZKTcd/GrnjTV5e40+ihmGLniajA2xSBbv44zN2bR5HARyrNC3DL6nZqMPGTiPZemuNX54LKA3/BNUF7FIdv1y/71XYx972qHVaVwet5FnTibwZWdTTbVH8u9G9gnAFdjyjeYGfvALIWKnN0C9eVehaZADhZTqUnNq9rim7a8lf9km4xvzho67YmWtE=
  app: rocky-inlet-18565
  on:
    repo: Naddinn/stringCalcWeb
