language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: UG1Kz0VpVMn6bchfKNQS0BX3I07F2Atg9jqb1kDqhwCdfuk8xhGSqCDM2IqiY5ayFJVX9N5M8htsCHiFvaAhdRp47k1Y0wA79FkSBiKu702x3593kXB9T/gzooRGo9S7/B1I34uNRKYM7IF1hkF/OvPdEegfl7JoIvqFA2jgcKJVH1YnETwQlftrj0bBD7bFtjZkqT+wGTr3mIluPsj18oseWns8EJWAWXU+WOR/W2bDoQ4Y22WS0O7pkbVq/vTMVau+/KB/Q6f086Ahb/V207GcYlh4FI/Sk3OPglbytGDFev3Ky4rdt4J8jWpuFSD0e8RjWB1yqCzILaPxDRqSnClsrz+hoI8VLJ0BnurHdRt5VrabXz6U7+DDoJx+iMG5pCioVTiFUidRgs+UegUVvALPq4F29miF/gPLASM6vXRx9UiGPZydxWs13DnJbiGejMZHEo8MVhOwaiQ0BwBd+VGBgOdWKl0hcjzM51PMnHTfKKGlQg8ftWu6nHMSoPD2OCCzigK8bV+Hbnt90YCIb/NotYBbtdrzVIqO2dBSY42UV9EQCwQXSgdL6/FlxdZaCpl4T7gYvcuYLTwMTVN+oPrZfS6Ymj6A0RzFjWkBH5/HGMhpqS6qeVylcVPAcvnit4jzo1n8ACXu7QVXj+FP/hfVwg0KpYfRvt45Vr6I0/k=
  app: sheltered-plateau-30331
  on:
    repo: Naddinn/stringCalcWeb

 notifications:
    slack: l2n3rd:Sxl7Uh3iXQFm37kA1b2iS2yI
